### PR TITLE
[MRG] Replace 'paradigm' with 'events', 'experimental paradigm' for BIDS compliance

### PR DESCRIPTION
**Pull request by kchawla-pi**
issue #216

### CODE REVIEW

**Comment by bthirion** [comment]
Let me know when it's ready for review.
Best,
B

**Comment by kchawla-pi** [comment]
It is now ready for review.

**Comment by kchawla-pi** [comment]
Uh circleci is failing. I'll check that, you can start on the review if you wish.

In some of your examples (newly merged/updated) I have :

- Replaced .csv file extension for events file with .tsv .
 - In examples, generally replaced paradigm.to_csv('paradigm.csv') with
 events.to_csv('events.tsv', sep='\t', index=False).

Do double check those.

**Comment by kchawla-pi** [comment]
The error seems similar to what Nilearn experienced: https://github.com/nilearn/nilearn/pull/1763

**Comment by kchawla-pi** [comment]
There's one modification in test_utils.py I forgot to make. I'll push that soon.

**Comment by kchawla-pi** [comment]
The error was occurring because I changed the name of the events file from `localizer_paradigm.csv` to `localizer_events.tsv` in the code without renaming the file itself first.
I will add that now.

**Comment by kchawla-pi** [comment]
Hey @bthirion that's file rename is causing problems right now and I think we have better goals to pursue. So I say we merge it this way. Maybe I can open a new PR to rename the events file tomorrow. WHat do you think?

**Comment by kchawla-pi** [comment]
FYI: In a few places I replaced events key with events columns in the doc strings.

**Comment by bthirion** [comment]
Merging now.

**Pull request merged**
