### PR TITLE
[MRG] Address design deficiencies in python deprecation functions & tests

### PR DESCRIPTION
**Pull request by kchawla-pi**
Lays the groundwork for addressing the issue raised in https://github.com/nilearn/nilearn/pull/1882#discussion_r241610908
Also
 - Simplifies testing the 2 deprecation functions.
 - Reduced redundant code.
 - Sets the stage for solving the glitch where importing Nistats in Py2, 3.4
 overrides the warnings filter of subsequent warnings & testing it.

### CODE REVIEW

**Comment by bthirion** [comment]
LGTM. Will merge tomorrow unless I hear otherwise.

**Comment by kchawla-pi** [comment]
Its not complete yet. The issue raised in https://github.com/nilearn/nilearn/pull/1882#discussion_r241610908 will be attended to next.

**Comment by kchawla-pi** [comment]
Okay, If this merged I will address the issue raised in https://github.com/nilearn/nilearn/pull/1882#discussion_r241610908 in a separate PR after this one is merged.

**Comment by kchawla-pi** [comment]
Not ready yet.

**Comment by kchawla-pi** [comment]
Hey @bthirion Its ready for another review.

**Pull request merged**
