### PR TITLE
Bump up min ver of libs no longer available in default conda channels

### PR DESCRIPTION
**Pull request by kchawla-pi**
- Bump minimum version of SciPy, SciKit-Learn to 0.19, libfortrang=3.0.1 (conda no longers supports lower versions in its default channel).

Remove warnings by

 - Install joblib as external library (no longer vendored in latest Scikit-Learn).
- Change `autodoc_default_flags` in Sphinx to `autodoc_default_options`

### CODE REVIEW

**Comment by kchawla-pi** [comment]
@bthirion Latest version of conda does not support Python 3.4 either. I vote for pinning conda to 4.6 and continuing development for Python2, 3.4 while we are still working in the Nistats repo.

**Comment by bthirion** [comment]
Looks like we have no other alternative ?

**Comment by jeromedockes** [comment]
why is it necessary to bump scikit-learn and scipy?
scikit-learn still supports scipy 0.17

**Comment by kchawla-pi** [comment]
Same discussion as Nilearn

**Comment by jeromedockes** [comment]
> Same discussion as Nilearn

https://github.com/nilearn/nilearn/pull/2078

**Comment by kchawla-pi** [comment]
Conda 4.75 does not support Python 3.4 . Since we are not dropping Python 2, 3.4 support until after pushing another release with GLM reporter merged, currently abandoning this and pinning conda to 4.6

**Pull request closed without merging**
