### PR TITLE
Updated minimum dependencies + miniconda URL

### PR DESCRIPTION
**Pull request by kchawla-pi**
Align with NiLearn, fix incorrect Pandas version

### CODE REVIEW

**Comment by kchawla-pi** [comment]
Pending: Removing references from code to older versions of the dependencies and updating What's New.

**Comment by bthirion** [comment]
LGTM. Any object to merging ?

**Comment by kchawla-pi** [comment]
Just the pending part above, I will solve that tomorrow.

**Comment by bthirion** [comment]
OK, I wait for it, then merge.

**Comment by KamalakerDadi** [comment]
LGTM.

**Comment by kchawla-pi** [comment]
I say we merge it now.

**Comment by bthirion** [comment]
Great. Merging now.
Thx, this is very important background maintenance.

**Pull request merged**
