### PR TITLE
CircleCI: Adding alt download for Brainomics data used in examples

### PR DESCRIPTION
**Pull request by kchawla-pi**

### CODE REVIEW

**Comment by bthirion** [comment]
LGTM, but why isn't this alternative location *yet* the default ?

**Comment by kchawla-pi** [comment]
Didn't get the time to integrate the alternate download location into our code, trying to get circleci to play nice on Nilearn is taking up all my time right now.

The present fix is a workaround for this sprint

**Comment by bthirion** [comment]
OK, this sounds like an easy todo for the sprint.
+1 for merging in any case.

**Comment by kchawla-pi** [comment]
Abandoned attempt to have an updating persistent cache for master branch.

**Pull request merged**
