### PR TITLE
Add cosine drifts with period up to equal to the requested cut period

### PR DESCRIPTION
**Pull request by takhs91**
Spawn of https://github.com/nipy/nipy/issues/448

Related to https://github.com/nipy/nipy/pull/449

### CODE REVIEW

**Comment by bthirion** [comment]
The changes LGTM, but it breaks the examples, probably due to some hard-coded parameters ;-(
Can you fix that too ?
Thx !

**Comment by takhs91** [comment]
Yes sure I will have a look! Do I have to update their output for the documentation too or is it done in the CI process?

**Comment by takhs91** [comment]
Yes I will have a look!

**Comment by bthirion** [comment]
Documentations output are generated automatically. You just need to make sure that the examples run correctly.

**Comment by takhs91** [comment]
Any additional steps?

**Comment by bthirion** [comment]
Merging, thx.

**Pull request merged**
