### PR TITLE
remove dependency on patsy

### PR DESCRIPTION
**Pull request by jeromedockes**
needed for merging into nilearn

### CODE REVIEW

**Comment by kchawla-pi** [comment]
FYI We don't have Flake8 checks in Nistats yet, PR pending, so you'll have to do it manually.

**Comment by jeromedockes** [comment]
> FYI We don't have Flake8 checks in Nistats yet, PR pending, so you'll have to do it manually.

do what?

**Comment by kchawla-pi** [comment]
Flake8 checks.
Its not automated so you will have to remember to do them.

**Comment by kchawla-pi** [comment]
You should remove Pasty from all 4 CI installations as well.

**Comment by jeromedockes** [comment]
> Flake8 checks.
> Its not automated so you will have to remember to do them.

thanks, done

**Pull request merged**
