### PR TITLE
FIX: CircleCI failure related to Sphinx 1.7

### PR DESCRIPTION
**Pull request by KamalakerDadi**
Attempts to FIX Sphinx 1.7 related issues with CircleCI. As we are seeing in this PR #167

### CODE REVIEW

**Comment by bthirion** [comment]
Seems to work. Can you add a pedagogical comment ()why this was done ?

**Comment by KamalakerDadi** [comment]
Directive is imported but not used anywhere. Moreover, module called util.compat is removed from Sphinx 1.7 that's the reason why the CircleCI is failing in other PRs.

**Comment by KamalakerDadi** [comment]
Should I add comment at removed place ? I don't understand if we really want to add a comment.

**Comment by bthirion** [comment]
Indeed, sorry.

**Comment by effigies** [comment]
Just FYI, `numpydoc` is now its own dependency you can include rather than bundle an old version of. See, e.g. https://github.com/nipy/nipype/pull/2437.

**Comment by KamalakerDadi** [comment]
@effigies Thanks. Good one! 

At some point, as a dependency of sphinx-gallery. We should upgrade to new version of sphinx-gallery which then I think would simply things as you pointed out.

**Pull request merged**
