### PR TITLE
TRAVIS use neurodebian on Ubuntu 14.04

### LINKED ISSUE #105: fix neurodebian installation in travis (problem with newer numpy version)
For the moment the neurodebian installation on Travis was commented out. The issues are due to trying to use a later numpy version in Travis with Neurodebian.

### PR DESCRIPTION
**Pull request by lesteve**
in order to have a numpy version that satisfies nistats requirements. Fix #105.

Instead of listing the build matrix in the env/matrix section, this uses the matrix/include section. This is the way shown in the Travis doc and this allows to run on Ubuntu 14.04 containers rather than the default 12.04 containers.

### CODE REVIEW

**Comment by lesteve** [comment]
I'll wait for the build to be green and merge this.

**Comment by lesteve** [comment]
I enabled CircleCI on PRs as well since it was not enabled.

**Comment by lesteve** [comment]
Everything was green, so merged.

**Comment by MartinPerez** [comment]
Awesome @lesteve, thanks for fixing this!

**Comment by bthirion** [comment]
Thx !

**Pull request merged**
