### PR TITLE
first level bids correction when sessions are present

### PR DESCRIPTION
**Pull request by MartinPerez**
A correction related to loading a BIDS dataset with sessions. There were some small issues and a print statement that was deleted.

### CODE REVIEW

**Comment by bthirion** [comment]
Feels good, but a small test to enforce the behavior would be great  !

**Comment by MartinPerez** [comment]
ok will add a test. Also several dependency chains seem broken, will look into.

**Comment by bthirion** [comment]
Let me suggest to put all dependencies version changes in a separate PR, that would be merged first.

**Comment by MartinPerez** [comment]
ok will separate them.

**Pull request closed without merging**
