### PR TITLE
Removed the unnecessary "General Examples" section

### PR DESCRIPTION
**Pull request by kchawla-pi**
Fix for #151 
Now getting a disappearing whitespace in its place.
The large whitespace is there if I scroll to the top of the page and disappears when I start scrolling down.
Ideas?

### CODE REVIEW

**Comment by bthirion** [comment]
OK, merging.

**Comment by kchawla-pi** [comment]
The work is incomplete. I will push more commits to this branch. I am getting transient extra whitespace that I haven't figured out how to remove.

**Comment by bthirion** [comment]
Ooops, I'll try a revert...

Note: please prepend "WIP" to the PR name if you think it's not ready for merge.

**Comment by bthirion** [comment]
So, I reverted it...

**Comment by kchawla-pi** [comment]
Currently the bg I am experiencing seems to be the Closed issue here
https://github.com/sphinx-gallery/sphinx-gallery/issues/226

**Comment by kchawla-pi** [comment]
Continued in PR #222

**Pull request merged**
