### PR TITLE
Update CircleCI from 1.0 to 2.0

### PR DESCRIPTION
**Pull request by kchawla-pi**
For #200

### CODE REVIEW

**Comment by kchawla-pi** [comment]
@KamalakerDadi @bthirion  review and merge please.

**Comment by KamalakerDadi** [comment]
We can completely remove old circle.yml file I think.

**Comment by KamalakerDadi** [comment]
Apart from my minor comment. LGTM

**Comment by kchawla-pi** [comment]
Dang it I missed that. Thanks

**Comment by bthirion** [comment]
LGTM. Merging when CircleCI is green.

**Comment by bthirion** [comment]
Merging, thx !

**Pull request merged**
